Repository MicrosoftDocs/azure-docs.pt-br, pull requests merged in 2019-06, with the labels that each got.

#347 Fix mistranslation
  articles/data-factory/v1/data-factory-pig-activity.md
Labels: Accepted

#344 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted

#345 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-sybase-connector.md
Labels: Accepted

#346 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted

#348 Fix mistranslation
  articles/data-factory/v1/data-factory-salesforce-connector.md
Labels: Accepted, Linguistic Suggestion

#349 Fix mistranslation
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Linguistic Suggestion

#350 Fix mistranslation
  articles/active-directory-b2c/configure-ropc.md
Labels: Accepted, Linguistic Suggestion

#351 Fix mistranslation
  articles/active-directory-b2c/ropc-custom.md
Labels: Accepted, Linguistic Suggestion

#352 Fix mistranslation
  articles/active-directory/develop/active-directory-claims-mapping.md
Labels: Accepted, Linguistic Suggestion

#355 Fix mistranslation
  articles/data-factory/v1/data-factory-stored-proc-activity.md
Labels: Accepted, Linguistic Suggestion

#354 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted, Linguistic Suggestion

#353 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted, Linguistic Suggestion

#356 Fix mistranslation
  articles/digital-twins/how-to-egress-endpoints.md
Labels: Accepted, Linguistic Suggestion

#359 Fix mistranslation
  articles/event-grid/event-schema-container-registry.md
Labels: Accepted, Linguistic Suggestion

#358 Fix mistranslation
  articles/event-grid/event-schema-blob-storage.md
Labels: Accepted, Linguistic Suggestion

#357 Fix mistranslation
  articles/event-grid/event-schema-azure-maps.md
Labels: Accepted, Linguistic Suggestion

#363 Fix mistranslation
  articles/event-grid/event-schema-service-bus.md
Labels: In Progress

#362 Fix mistranslation
  articles/event-grid/event-schema-resource-groups.md
Labels: In Progress

#361 Fix mistranslation
  articles/event-grid/event-schema-iot-hub.md
Labels: In Progress

#360 Fix mistranslation
  articles/event-grid/event-schema-event-hubs.md
Labels: In Progress

#368 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: In Progress

#367 Fix mistranslation
  articles/event-grid/subscription-creation-schema.md
Labels: In Progress

#366 Fix mistranslation
  articles/event-grid/event-schema.md
Labels: In Progress

#365 Fix mistranslation
  articles/event-grid/event-schema-subscriptions.md
Labels: In Progress

#369 Fix mistranslation
  articles/iot-hub/iot-hub-device-sdk-c-serializer.md
Labels: In Progress

#370 Fix mistranslation
  articles/lab-services/devtest-lab-artifact-author.md
Labels: In Progress

#371 Fix mistranslation
  articles/logic-apps/logic-apps-custom-api-authentication.md
Labels: In Progress

#372 Update ingress-tls.md
  articles/aks/ingress-tls.md
Labels: In Progress

#373 Correct Node name
  includes/functions-supported-languages.md
Labels: Accepted, Linguistic Suggestion

#364 Fixed Node.js translation
  articles/azure-functions/functions-reference-node.md
Labels: Accepted, Linguistic Suggestion

#374 Fix mistranslation
  articles/logic-apps/logic-apps-exception-handling.md
Labels: In Progress

#375 Fix mistranslation
  articles/logic-apps/logic-apps-handle-large-messages.md
Labels: In Progress

#376 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-as2-tracking-schemas.md
Labels: In Progress

#377 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-custom-tracking-schema.md
Labels: In Progress

#378 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-x12-tracking-schema.md
Labels: In Progress

#379 Fix mistranslation
  articles/managed-applications/create-uidefinition-elements.md
Labels: In Progress

#380 Fix mistranslation
  articles/media-services/previous/media-services-motion-detection.md
Labels: In Progress

#381 Fix mistranslation
  articles/service-fabric/service-fabric-sfctl-application.md
Labels: In Progress

#382 Fix mistranslation
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension.md
Labels: In Progress

#387 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-linux.md
Labels: In Progress

#386 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-windows.md
Labels: In Progress

#385 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-linux.md
Labels: In Progress

#384 Fix mistranslation
  articles/service-fabric/service-fabric-cluster-nodetypes.md
Labels: In Progress

#383 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: In Progress

#388 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-windows.md
Labels: In Progress

#390 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: In Progress

#391 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linuxOstc.md
Labels: Accepted

#393 Fix mistranslation
  articles/virtual-machines/extensions/dsc-template.md
Labels: Accepted, Linguistic Suggestion

#395 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-linux.md
Labels: Accepted, Linguistic Suggestion

#394 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: Accepted, Linguistic Suggestion

#396 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-windows.md
Labels: In Progress

#399 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/BingVoiceOutput.md
Labels: In Progress

#398 Fix mistranslation
  articles/virtual-machines/extensions/oms-windows.md
Labels: In Progress

#397 Fix mistranslation
  articles/virtual-machines/extensions/oms-linux.md
Labels: In Progress

#404 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: In Progress

#403 Fix mistranslation
  articles/analysis-services/analysis-services-async-refresh.md
Labels: In Progress

#402 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: In Progress

#401 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-blob-connector.md
Labels: In Progress

#400 Fix mistranslation
  articles/data-factory/v1/data-factory-amazon-simple-storage-service-connector.md
Labels: In Progress

#408 Fix mistranslation
  articles/governance/blueprints/reference/blueprint-functions.md
Labels: In Progress

#405 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-deployment.md
Labels: In Progress

#406 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: In Progress

#407 Fix mistranslation
  articles/data-factory/control-flow-if-condition-activity.md
Labels: In Progress

#411 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-actions-triggers.md
Labels: Accepted

#412 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-definition-language.md
Labels: Accepted, Linguistic Suggestion

#410 typo: lauch -> launch
  articles/active-directory/saas-apps/launchdarkly-tutorial.md
Labels: In Progress

#413 Fix mistranslation
  articles/logic-apps/workflow-definition-language-functions-reference.md
Labels: Accepted

#414 Fix mistranslation
  articles/media-services/latest/media-services-event-schemas.md
Labels: Accepted, Linguistic Suggestion

#416 Fix mistranslation
  articles/active-directory/conditional-access/technical-reference.md
Labels: Accepted

#417 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted

#419 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted, Linguistic Suggestion

#418 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#420 Fix mistranslation
  articles/azure-monitor/insights/solutions-solution-file.md
Labels: Accepted, Linguistic Suggestion

#422 Fix mistranslation
  articles/azure-monitor/log-query/unify-app-resource-data.md
Labels: Accepted

#423 Fix mistranslation
  articles/azure-monitor/platform/activity-log-export.md
Labels: Accepted

#424 Fix mistranslation
  articles/azure-monitor/platform/alerts-webhooks.md
Labels: Accepted

#425 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted
