Repository MicrosoftDocs/azure-docs.pt-br, pull requests merged in 2019-05, with the labels that each got.

#260 Fix mistranslation
  articles/azure-functions/functions-bindings-http-webhook.md
Labels: Accepted, In Progress

#262 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, In Progress

#264 Fix mistranslation
  articles/billing/billing-review-subscription-billing.md
Labels: Accepted, In Progress

#265 Fix mistranslation
  articles/data-factory/connector-amazon-marketplace-web-service.md
Labels: Accepted, In Progress

#267 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, In Progress

#270 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, In Progress

#268 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, In Progress

#266 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, In Progress

#269 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db-mongodb-api.md
Labels: Accepted, In Progress

#271 Fix mistranslation
  articles/data-factory/connector-azure-data-explorer.md
Labels: Accepted, In Progress

#272 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, In Progress

#273 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: In Progress

#276 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted, In Progress

#277 Fix mistranslation
  articles/data-factory/connector-cassandra.md
Labels: Accepted, In Progress

#261 grammar corrections
  articles/cosmos-db/partitioning-overview.md
Labels: Accepted, Linguistic Suggestion

#279 Fix mistranslation
  articles/data-factory/connector-concur.md
Labels: Accepted, In Progress

#280 Fix mistranslation
  articles/data-factory/connector-db2.md
Labels: Accepted, In Progress

#281 Fix mistranslation
  articles/data-factory/connector-dynamics-ax.md
Labels: Accepted, In Progress

#283 Fix mistranslation
  articles/data-factory/connector-file-system.md
Labels: Accepted, In Progress

#282 Fix mistranslation
  articles/data-factory/connector-dynamics-crm-office-365.md
Labels: Accepted, In Progress

#284 Fix mistranslation
  articles/data-factory/connector-ftp.md
Labels: Accepted, In Progress

#285 Fix mistranslation
  articles/data-factory/connector-google-bigquery.md
Labels: Accepted, In Progress

#287 Fix mistranslation
  articles/data-factory/connector-hbase.md
Labels: Accepted, In Progress

#288 Fix mistranslation
  articles/data-factory/connector-hdfs.md
Labels: Accepted, In Progress

#289 Fix mistranslation
  articles/data-factory/connector-hive.md
Labels: Accepted, In Progress

#290 Fix mistranslation
  articles/data-factory/connector-http.md
Labels: Accepted, In Progress

#291 Fix mistranslation
  articles/data-factory/connector-impala.md
Labels: Accepted, In Progress

#293 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, In Progress

#292 Fix mistranslation
  articles/data-factory/connector-jira.md
Labels: Accepted, In Progress

#274 correção da tradução
  articles/azure-functions/functions-dotnet-dependency-injection.md
Labels: Linguistic Suggestion, Partially Accepted

#294 Fix mistranslation
  articles/data-factory/connector-mongodb.md
Labels: Accepted, In Progress

#295 Fix mistranslation
  articles/data-factory/connector-netezza.md
Labels: Accepted, In Progress

#296 Fix mistranslation
  articles/data-factory/connector-odata.md
Labels: Accepted, In Progress

#297 Fix mistranslation
  articles/data-factory/connector-odbc.md
Labels: Accepted, In Progress

#298 Fix mistranslation
  articles/data-factory/connector-oracle-eloqua.md
Labels: Accepted, In Progress

#299 Fix mistranslation
  articles/data-factory/connector-oracle-service-cloud.md
Labels: Accepted, In Progress

#300 Fix mistranslation
  articles/data-factory/connector-oracle.md
Labels: Accepted, In Progress

#278 Transalation corretions
  articles/app-service/overview-managed-identity.md
Labels: Linguistic Suggestion, Partially Accepted

#301 Fix mistranslation
  articles/data-factory/connector-phoenix.md
Labels: Accepted, In Progress

#302 Fix mistranslation
  articles/data-factory/connector-presto.md
Labels: Accepted, In Progress

#303 Fix mistranslation
  articles/data-factory/connector-rest.md
Labels: Accepted, In Progress

#304 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted, In Progress

#305 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse-open-hub.md
Labels: Accepted, In Progress

#306 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted, In Progress

#307 Fix mistranslation
  articles/data-factory/connector-sap-cloud-for-customer.md
Labels: Accepted, In Progress

#308 Fix mistranslation
  articles/data-factory/connector-sap-ecc.md
Labels: Accepted, In Progress

#310 Fix mistranslation
  articles/data-factory/connector-servicenow.md
Labels: Accepted, In Progress

#309 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, In Progress

#311 Fix mistranslation
  articles/data-factory/connector-sftp.md
Labels: Accepted, In Progress

#312 Update contoso-migration-rehost-vm-sql-ag.md
  articles/migrate/contoso-migration-rehost-vm-sql-ag.md
Labels: In Progress

#313 Fix mistranslation
  articles/data-factory/connector-spark.md
Labels: Accepted, In Progress

#314 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress

#315 Fix mistranslation
  articles/data-factory/connector-sybase.md
Labels: Accepted, In Progress

#316 Fix mistranslation
  articles/data-factory/connector-teradata.md
Labels: Accepted, Linguistic Suggestion

#317 Fix mistranslation
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Linguistic Suggestion

#318 Fix mistranslation
  articles/data-factory/copy-activity-schema-and-type-mapping.md
Labels: Accepted, Linguistic Suggestion

#319 Fix mistranslation
  articles/data-factory/how-to-create-tumbling-window-trigger.md
Labels: Accepted, Linguistic Suggestion

#320 Fix mistranslation
  articles/data-factory/monitor-using-azure-monitor.md
Labels: Accepted, Linguistic Suggestion

#321 Fix mistranslation
  articles/data-factory/store-credentials-in-key-vault.md
Labels: Accepted, Linguistic Suggestion

#323 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: Accepted, Linguistic Suggestion

#322 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-documentdb-connector.md
Labels: Accepted, Linguistic Suggestion

#324 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-powershell.md
Labels: Accepted, Linguistic Suggestion

#325 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-rest-api.md
Labels: Accepted, In Progress

#328 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-rest-api.md
Labels: Accepted, In Progress

#327 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-powershell.md
Labels: Accepted, In Progress

#329 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-visual-studio.md
Labels: Accepted, In Progress

#330 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, In Progress

#326 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-azure-portal.md
Labels: Accepted, In Progress

#332 Fix mistranslation
  articles/data-factory/v1/data-factory-ftp-connector.md
Labels: Accepted, Linguistic Suggestion

#333 Fix mistranslation
  articles/data-factory/v1/data-factory-hdfs-connector.md
Labels: Accepted, Linguistic Suggestion

#331 Fix mistranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Linguistic Suggestion

#334 Fix mistranslation
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted, Linguistic Suggestion

#335 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted, Linguistic Suggestion

#336 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted, Linguistic Suggestion

#337 Fix mistranslation
  articles/data-factory/v1/data-factory-map-reduce.md
Labels: Accepted, Linguistic Suggestion

#341 Fix mistranslation
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, In Progress

#342 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-file-system-connector.md
Labels: Accepted, In Progress

#343 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-mysql-connector.md
Labels: Accepted, In Progress
