Repository MicrosoftDocs/azure-docs.pt-br, pull requests merged in 2019-04, with the labels that each got.

#219 updated provision-deep-learning-dsvm.md
  articles/machine-learning/data-science-virtual-machine/provision-deep-learning-dsvm.md
Labels: Accepted, Source Issue

#222 Fixing translation errors
  articles/virtual-machines/windows/index.yml
Labels: Accepted, Linguistic Suggestion

#229 Fix mistranslation
  articles/azure-monitor/platform/api-alerts.md
Labels: Accepted, In Progress

#228 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted, In Progress

#227 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, In Progress

#226 Fix mistranslation
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, In Progress

#234 Fix mistranslation
  articles/data-factory/connector-azure-search.md
Labels: Accepted, In Progress, Linguistic Suggestion

#233 Fix mistranslation
  articles/azure-monitor/platform/archive-diagnostic-logs.md
Labels: Accepted, In Progress, Linguistic Suggestion

#232 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress, Linguistic Suggestion

#231 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted, In Progress, Linguistic Suggestion

#235 Fix mistranslation
  articles/azure-monitor/insights/wire-data.md
Labels: Accepted, In Progress, Linguistic Suggestion

#236 Fix mistranslation
  articles/azure-monitor/platform/activity-logs-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#237 Fix mistranslation
  articles/data-factory/connector-azure-sql-database-managed-insance.md
Labels: Accepted, In Progress, Linguistic Suggestion

#238 Fix mistranslation
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, In Progress, Linguistic Suggestion

#241 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, In Progress

#240 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted, In Progress

#244 Fix mistranslation
  articles/azure-maps/geofence-geojson.md
Labels: Accepted, In Progress

#243 Fix mistranslation
  articles/api-management/api-management-product-templates.md
Labels: Accepted, In Progress

#249 Fix mistranslation
  articles/automation/automation-manage-send-joblogs-log-analytics.md
Labels: Accepted, In Progress

#248 Fix mistranslation
  articles/automation/automation-solution-vm-management.md
Labels: Accepted, In Progress

#247 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, In Progress

#246 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#245 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, In Progress

#252 Fix mistranslation
  articles/api-management/api-management-howto-use-azure-monitor.md
Labels: Accepted, In Progress

#251 Fix mistranslation
  articles/automation/automation-dsc-diagnostics.md
Labels: Accepted, In Progress

#250 Fix mistranslation
  articles/data-factory/control-flow-filter-activity.md
Labels: Accepted, In Progress

#257 Fix mistranslation
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, In Progress

#256 Fix mistranslation
  articles/azure-monitor/insights/vminsights-log-search.md
Labels: Accepted, In Progress

#255 Fix mistranslation
  articles/data-factory/connector-web-table.md
Labels: Accepted, In Progress

#254 Fix mistranslation
  articles/api-management/api-management-howto-properties.md
Labels: Accepted, In Progress

#253 Fix mistranslation
  articles/api-management/api-management-error-handling-policies.md
Labels: Accepted, In Progress

#259 Fix mistranslation
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, In Progress
