Repository MicrosoftDocs/azure-docs.pt-br, pull requests merged in 2019-07, with the labels that each got.

#426 Fix mistranslation
  articles/azure-monitor/platform/autoscale-webhook-email.md
Labels: Accepted

#427 Fix mistranslation
  articles/azure-monitor/platform/powershell-quickstart-samples.md
Labels: Accepted

#429 Fix mistranslation
  articles/blockchain/service/send-transaction.md
Labels: Accepted

#428 Fix mistranslation
  articles/blockchain/service/manage-consortium-powershell.md
Labels: Accepted

#430 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#431 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted, Linguistic Suggestion

#433 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, Linguistic Suggestion

#432 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, Linguistic Suggestion

#436 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted

#437 Fix mistranslation
  articles/hdinsight/domain-joined/apache-domain-joined-create-configure-enterprise-security-cluster.md
Labels: Accepted

#435 Fix typo
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted

#439 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-customize-cluster-linux.md
Labels: Accepted

#438 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
Labels: Accepted

#440 Fix mistranslation
  articles/mariadb/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#441 Fix mistranslation
  articles/mariadb/tutorial-design-database-cli.md
Labels: Accepted, Linguistic Suggestion

#443 Fix mistranslation
  articles/postgresql/howto-restore-server-cli.md
Labels: Accepted, Linguistic Suggestion

#442 Fix mistranslation
  articles/mysql/tutorial-design-database-using-cli.md
Labels: Accepted, Linguistic Suggestion

#444 Fix mistranslation
  articles/postgresql/tutorial-design-database-using-azure-cli.md
Labels: Accepted, Linguistic Suggestion

#445 Fix mistranslation
  articles/traffic-manager/traffic-manager-powershell-arm.md
Labels: Accepted

#446 Fix mistranslation
  articles/app-service-mobile/app-service-mobile-ios-get-started-offline-data.md
Labels: Accepted

#447 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, Linguistic Suggestion

#448 Fix mistranslation
  articles/storage/common/storage-powershell-independent-clouds.md
Labels: Accepted, Linguistic Suggestion

#449 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Linguistic Suggestion

#450 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted

#451 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted

#452 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#453 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted

#454 Fix mistranslation
  articles/azure-resource-manager/resource-group-authoring-templates.md
Labels: Accepted

#457 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-string.md
Labels: Accepted

#456 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: Accepted

#458 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#459 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: Accepted

#460 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted

#461 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: Accepted

#462 Fix mistranslation
  articles/data-factory/connector-amazon-marketplace-web-service.md
Labels: Accepted, Linguistic Suggestion

#463 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, Linguistic Suggestion

#466 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted

#467 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, Linguistic Suggestion

#468 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted

#464 Update index.yml
  articles/virtual-desktop/index.yml
Labels: Linguistic Suggestion, Partially Accepted

#471 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted
